export const  rows = [
  {
    id: "1",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "1",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "1",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "1",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "2",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "2",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "2",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "2",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "3",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "3",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Flat Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "3",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Negotiated Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "3",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Negotiated Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "4",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Negotiated Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "4",
    entity: "Male",
    category: "Residential",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Negotiated Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "4",
    entity: "Male",
    category: "Commercial",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Negotiated Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "4",
    entity: "Male",
    category: "Commercial",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Negotiated Split",
    interestBids: "0",
    action: "testFunction",
  },
  {
    id: "nnn",
    entity: "Male",
    category: "Commercial",
    type: "Buyer",
    referrer: "Jamiel Sheikh",
    jurisdiction: "NY",
    region: "LES",
    potentialDealSize: "$2,287,500",
    potentialGci: "$36,000",
    awardMethod: "Negotiated Split",
    interestBids: "0",
    action: "testFunction",
  }
]